# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHVtZq2BzLL0sGG8g2xGjW70d9pJlo-8
"""

letras = {'a','b','c'}
print (type(letras))

letras = set()
print (type(letras))

letras = {}
print (type(letras))

letras = {'a','b','c','a','d','c','a','f','g'}
print (letras)
{'a', 'c', 'f', 'b', 'd', 'g'}

frutas = ['uva', 'maça','tangerina','uva', ]
print (f'aqui frutas estao em uma lista: {frutas}')
frutas = set(frutas)
print(f'agora frutas estao em uma lista: {frutas}')

web = {'html','javascritp','python','css'}
mobile = {'flutter','python','kotlin','javascript'}
diferenca = web.difference(mobile)
print(diferenca)

A = {1, 2, 3}
B = {4, 5, 6}
C = {6, 7, 8}

print('A and B are disjoint:', A.isdisjoint(B))
print('B and C are disjoint:', B.isdisjoint(C))

a = {1,2,3,4}
b = {1,4,5,6}
c = a.union(b)
c

print(a.intersection(b))

type(a)

A = {1, 2, 3}
B = {4, 5, 6}
C = {6, 7, 8}
D = {9,10,11}
E = {12,13,14}

print('A and B are disjoint:', A.isdisjoint(B))
print('B and C are disjoint:', B.isdisjoint(C))
print('C and D are disjoint:', C.isdisjoint(D))
print('D and E are disjoint:', D.isdisjoint(E))

set1 = {'Carro','arroz','lamboghine'}
set2 = {1, 5, 7, 9, 3}
set3 = {True, False, False}
set1 = {1, 5, 7, 9, 3}
print(set)

s3={1,5,7,9,3}
print(s3)
s3.discard(5)
s3

times = ['borussia monchengladbach','real madrid','chelsea','barcelona',]
print(f'aqui times estao em uma lista: {times}')
times = set(times)
print(f'agora times estao em uma lista: {times}')

times = ['borussia monchengladbach','real madrid','chelsea','barcelona',]
print(f'aqui times estao em uma lista: {times}')
times = set(times)
print(f'agora times estao em uma lista: {times}')
times = {'borussia monchengladbach','real madrid','chelsea','barcelona'}
times.remove('real madrid')
print(times)
a = {'borussia','real madrid','chelsea','barcelona'}
b = {'machester unite','bayern','chelsea','barcelona'}
c = a.union(b)
c